### ISSUE TITLE
doc thing

### ISSUE THREAD

**Issue by wwood** [AroneyS/binchicken#103]
In the README

>Paired end reads of form reads_1.1.fq, reads_1_1.fq and reads_1_R1.fq 

Isn't the 1st one repeated then? Do you mean reads_1.fastq.gz ? What about reads.1.fq.gz for instance?

Also,

> Most intermediate files can be provided to skip those steps

Which steps is this talking about?

I think it would be good to have a documentation section specifically about threads / RAM. It is very confusing with lots of options e.g. -c and threads per process, different steps etc. (especially when you add in retrying)

**Comment by AroneyS** [comment]
1. They are examples of formatting for the forward vs reverse reads. The reads_1 is just an example sample name. Maybe it should instead read `*.1.fq, *_1.fq, *_R1.fq`. This just applies to parsing SingleM outputs. Bin chicken just takes the longest string that is identical between the paired reads.

2. A chunk of the options are for intermediate files. e.g. read/genome SingleM otu tables, SingleM query, read sizes and genome transcripts. I can add more information.

3. I can draft something up. There are a lot of moving parts so its hard to summarise simply.
