### ISSUE TITLE
target_elusive needed with single sample assembly

### ISSUE THREAD

**Issue by wwood** [AroneyS/binchicken#104]
When there's nothing specific being targeted, everything is unbinned, so this rule doesn't seem to achieve a lot conceptually (I think - everything is "elusive"?), and just takes extra time. Maybe not a big deal, unless it gets stuck in the queue..

**Comment by AroneyS** [comment]
Maybe I need to rename it, but target_elusive does the sequence matching across samples in addition to elusive filtering. So it is required even in single-sample mode to find the recovery samples.
