### ISSUE TITLE
Conda installation challenge

### ISSUE THREAD

**Issue by hhollandmoritz** [AroneyS/binchicken#126]
Hi @AroneyS,

I was trying to install this via conda using the command specified in documentation and got an error:

```
conda create -n binchicken -c bioconda -c conda-forge binchicken
UnsatisfiableError: The following specifications were found to be incompatible with your system:

  - feature:/linux-64::__glibc==2.28=0
  - binchicken -> pyarrow=12.0 -> __glibc[version='>=2.17,<3.0.a0']

Your installed version is: 2.28
```

I fixed it by first creating the environment from the binchicken.yml file, then installing binchicken from conda after that environment was set up. I think it might be an issue with the order of conda-forge and bioconda being different between the .yml and instructions in the documentation. But I didn't spend much time trying to figure it out. 

Cheers!
Hannah

**Comment by AroneyS** [comment]
I can't replicate this, what system are you on? Can you try reversing the order?

**Comment by wwood** [comment]
Hi @hhollandmoritz try using mamba instead of conda. That might provide a better error message - your error looks something like this https://stackoverflow.com/questions/71546900/weird-glibc-2-17-conflict-when-trying-to-conda-install-tensorflow-1-4-1

And mamba just seems to work better in general - been using it not conda for yonks.

**Comment by hhollandmoritz** [comment]
This is on our HPC system, which is running a fedora-flavor of linux. It's running conda 4.10.3. I'm not sure I can use mamba on it (probably it will be fine, I just haven't yet tried and it's a shared system), but changing the order of the channels worked! 

In case it's relevant, here's the system info.
```
NAME="Rocky Linux"
VERSION="8.9 (Green Obsidian)"
ID="rocky"
ID_LIKE="rhel centos fedora"
VERSION_ID="8.9"
PLATFORM_ID="platform:el8"
PRETTY_NAME="Rocky Linux 8.9 (Green Obsidian)"
ANSI_COLOR="0;32"
LOGO="fedora-logo-icon"
CPE_NAME="cpe:/o:rocky:rocky:8:GA"
HOME_URL="https://rockylinux.org/"
BUG_REPORT_URL="https://bugs.rockylinux.org/"
SUPPORT_END="2029-05-31"
ROCKY_SUPPORT_PRODUCT="Rocky-Linux-8"
ROCKY_SUPPORT_PRODUCT_VERSION="8.9"
REDHAT_SUPPORT_PRODUCT="Rocky Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="8.9"
```
