### ISSUE TITLE
Illegal instruction (core dumped)

### ISSUE THREAD

**Issue by cliffbueno** [AroneyS/binchicken#135]
Hello,

I installed binchicken with conda, activated the environment, and tried running the coassemble function and got the error:
"Illegal instruction (core dumped)"
As far as I can tell, this might be an issue with our server CPU being too old to run binchicken? Is that true? Thank you for any insights you may have.

Thanks,

Cliff

**Comment by AroneyS** [comment]
I haven't seen that before. Do `binchicken -h` or `binchicken build` work? Does the error have any other text?

**Comment by cliffbueno** [comment]
Those don't work either (same error) and there is no other text. I'm going to try on the university supercomputer which should be better than our lab server anyway.

**Comment by AroneyS** [comment]
Yeh, weird. Does python run?

**Comment by cliffbueno** [comment]
Yes python runs.

**Comment by AroneyS** [comment]
Can you import all these manually in python?

```
import os
import sys
import logging
import subprocess
import extern
import importlib.resources
import bird_tool_utils as btu
import polars as pl
import polars.selectors as cs
from polars.exceptions import NoDataError
from snakemake.io import load_configfile
from ruamel.yaml import YAML
import copy
import shutil
```

**Comment by cliffbueno** [comment]
ModuleNotFoundError: No module named 'extern'

**Comment by AroneyS** [comment]
Ok, so it hasn't installed properly. Some people have had issues with `conda`. Do you have `mamba` available?
e.g. `mamba create -n binchicken -c bioconda -c conda-forge binchicken`

**Comment by cliffbueno** [comment]
Thanks for the help, I got it working on the supercomputer so not going to troubleshoot this further, but mamba is a good idea.
